### ISSUE TITLE
Support for custom resources

### ISSUE THREAD

**Issue by RuneKR** [lantanagroup/FHIR.js#1]
FHIR allows for adding custom resources and define bindings to etc snomed ct. Do you plan on add this future or do you want help with that?

**Comment by seanmcilvenna** [comment]
Assuming I understand you correctly, this is already implemented.
You can create profiles for any of the base resource types in FHIR DSTU1/2 and STU3. You can define constraints on the profiles that "specialize" it from the base resource. Those constraints can include bindings, such as value sets, code systems and single values (ex: a specific code).
The "View" screen for a template/profile shows the "StructureDefinition" representation of the profile.
Are there other features you are referring to that I missed?

**Comment by MedSolve** [comment]
You are correct, that was the features i was looking for. I was going through everything on my phone, here on github, and i did not find that functionality explicitly stated in the documentation.
I will look more closely through the code and documentation to locate these features.
Thank you
-------- Oprindelig besked --------Fra: Sean McIlvenna <notifications@github.com> Dato: 09/12/2016  09.41  (GMT+12:00) Til: "lantanagroup/FHIR.js" <FHIR.js@noreply.github.com> Cc: MedSolve <rune@medsolve.dk>, Author <author@noreply.github.com> Emne: Re: [lantanagroup/FHIR.js] Support for custom resources (#1) 
Assuming I understand you correctly, this is already implemented.

You can create profiles for any of the base resource types in FHIR DSTU1/2 and STU3. You can define constraints on the profiles that "specialize" it from the base resource. Those constraints can include bindings, such as value sets, code systems and single values (ex: a specific code).

The "View" screen for a template/profile shows the "StructureDefinition" representation of the profile.

Are there other features you are referring to that I missed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lantanagroup/FHIR.js","title":"lantanagroup/FHIR.js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lantanagroup/FHIR.js"}},"updates":{"snippets":[{"icon":"PERSON","message":"@seanmcilvenna in #1: Assuming I understand you correctly, this is already implemented.\r\nYou can create profiles for any of the base resource types in FHIR DSTU1/2 and STU3. You can define constraints on the profiles that \"specialize\" it from the base resource. Those constraints can include bindings, such as value sets, code systems and single values (ex: a specific code).\r\nThe \"View\" screen for a template/profile shows the \"StructureDefinition\" representation of the profile.\r\nAre there other features you are referring to that I missed?"}],"action":{"name":"View Issue","url":"https://github.com/lantanagroup/FHIR.js/issues/1#issuecomment-265849469"}}}

**Comment by seanmcilvenna** [comment]
Sorry MedSolve, I misread the email subject thinking this was for a different product.
You are right, FHIR.js does not yet support profiles (StructureDefinition). The primary purpose for the module at this time is for serialization to and from XML and JSON/JS. I would like to add support for profiles, but can't guarantee when that will happen.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by seanmcilvenna** [comment]
Can you provide me an example of what custom resources and bindings you are wanting FHIR.js to handle?

**Comment by MedSolve** [comment]
The idea of custom resources or profiles are as of the specified in the HL7 FHIR standard. I have no specifics in mind and therefore no example. In some use cases especially within the Danish healthcare system there are in great need for profiles and and also ValueSets like our national Snomed CT mapping. 

Setting up a tutorial and system system so that i can create or bind to my own value sets amongst auto generate a conformance of my implementation would be pure gold.

**Comment by seanmcilvenna** [comment]
Hi @MedSolve, Yes, I understand _what_ custom resources are, I was just wondering if you had a specific example for me to make sure your use-case is met. I will use the standard as my reference for this feature, though. Thank you
