### ISSUE TITLE
Plans for 4.0.0?

### ISSUE THREAD

**Issue by stbowden** [lantanagroup/FHIR.js#14]
With FHIR R4 (4.0.0) having been released at the end of 2018, is there a roadmap for getting FHIR.js updated to support it out of the box? With R4/4.0.0 providing the first normative content within the standard, it's a much more compelling target for supporting it in new applications.

Thanks!

**Comment by seanmcilvenna** [comment]
Actually, the project has already been updated to support the 4.0.0 models, I just forgot to update the README.md. I'm in the process of updating it, now... But I'm gonna hold off on publishing a 4.5.1 version until I have some substantive functional changes to the code, rather than just a README update. So, github will reflect the changes to the README, but NPM will (incorrectly) show FHIR version 3.4.0.
